// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protoc.mobile.proto

package protoc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Mobile struct {
	Brand                string   `protobuf:"bytes,1,opt,name=brand,proto3" json:"brand,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Mobile) Reset()         { *m = Mobile{} }
func (m *Mobile) String() string { return proto.CompactTextString(m) }
func (*Mobile) ProtoMessage()    {}
func (*Mobile) Descriptor() ([]byte, []int) {
	return fileDescriptor_84d97a9b45caba9d, []int{0}
}

func (m *Mobile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Mobile.Unmarshal(m, b)
}
func (m *Mobile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Mobile.Marshal(b, m, deterministic)
}
func (m *Mobile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Mobile.Merge(m, src)
}
func (m *Mobile) XXX_Size() int {
	return xxx_messageInfo_Mobile.Size(m)
}
func (m *Mobile) XXX_DiscardUnknown() {
	xxx_messageInfo_Mobile.DiscardUnknown(m)
}

var xxx_messageInfo_Mobile proto.InternalMessageInfo

func (m *Mobile) GetBrand() string {
	if m != nil {
		return m.Brand
	}
	return ""
}

func init() {
	proto.RegisterType((*Mobile)(nil), "protoc.Mobile")
}

func init() { proto.RegisterFile("protoc.mobile.proto", fileDescriptor_84d97a9b45caba9d) }

var fileDescriptor_84d97a9b45caba9d = []byte{
	// 74 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2e, 0x28, 0xca, 0x2f,
	0xc9, 0x4f, 0xd6, 0xcb, 0xcd, 0x4f, 0xca, 0xcc, 0x49, 0xd5, 0x03, 0xf3, 0x84, 0xd8, 0x20, 0x82,
	0x4a, 0x72, 0x5c, 0x6c, 0xbe, 0x60, 0x71, 0x21, 0x11, 0x2e, 0xd6, 0xa4, 0xa2, 0xc4, 0xbc, 0x14,
	0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x08, 0x27, 0x09, 0xa2, 0xce, 0x18, 0x10, 0x00, 0x00,
	0xff, 0xff, 0xf9, 0xbf, 0x06, 0xaf, 0x45, 0x00, 0x00, 0x00,
}
